### ISSUE TITLE
inet-henge.js:141 Uncaught TypeError: Cannot read property 'nodes' of undefined

### ISSUE THREAD

**Issue by godlovejanson** [codeout/inet-henge#1]
inet-henge.js:141 Uncaught TypeError: Cannot read property 'nodes' of undefined
why?

**Comment by codeout** [comment]
I think your json is possibly broken. Could you make sure that it's valid or show me your json data to test?

**Comment by godlovejanson** [comment]
I run your example,the question is still.

**Comment by godlovejanson** [comment]
i hava send a email to your goodies@codeout.net, please check it. Thanks!

**Comment by codeout** [comment]
If you are using Chrome, you might see an error ```Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.``` in developer console, which means that Chrome rejected local json for security reasons.

* Try firefox ( I haven't tested on IE family )
* Try web-hosted json
  * Heroku based [demo site](https://inet-henge.herokuapp.com/)

**Comment by godlovejanson** [comment]
I cannot open demo site.
I hava an another question,can your project use remote json（which is obtained by ajax）? how?

**Comment by codeout** [comment]
Yes, it's designed to fetch remote json internally. You can specify the URL in ```new Diagram()``` like this:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <link href="style.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.17/d3.js"></script>
    <script src="../vendor/cola.min.js"></script>
    <script src="../inet-henge.js"></script>
  </head>

  <body>
    <div id="diagram"></div>
  </body>

  <script>
   var diagram = new Diagram('#diagram', 'https://inet-henge.herokuapp.com/data/shownet.json', {pop: /^([^\s-]+)-/});
   diagram.init('loopback', 'interface');
  </script>
</html>
```

Please note that .js and .json should be hosted in the same domain or appropriately configure your server for CORS. Chrome might reject cross-origin request with default server configuration while Firefox will allow.
