### ISSUE TITLE
Add label on the links

### ISSUE THREAD

**Issue by Vito96** [codeout/inet-henge#11]
Hi,
Is it possibile add a label for every links?

Thanks a lot.

**Comment by codeout** [comment]
Thanks for asking, you can do this by adding `"meta"` data to every link like this:

```html
# html
new Diagram('#diagram', 'index.json').init('bandwidth');
```

```js
# index.json
...
  "links": [
    {
      "source": "Node 1", "target": "Node 2",
      "meta": {"bandwidth": "10G"}
    }
  ]
...
```

See https://github.com/codeout/inet-henge#labels for details.
