### ISSUE TITLE
Node name in pop

### ISSUE THREAD

**Issue by linascheryservers** [codeout/inet-henge#12]
Hi,
Nice project for dynamic network map drawing :+1: 
Is it possible to remove pop name from node name in pop? 
e.g. full node names in shownet.json is "dceast-ne40e", "dceast-fx1-1", they are grouped to pop "dceast", but individual nodes in pop "dceast" could be named "ne40e", "fx1-1"

**Comment by codeout** [comment]
Hi, thank you for using inet-henge.

I've just introduced a signal to hook when inet-henge completes rendering the diagram.
With the newest version, you can rename nodes like this:

```diff
--- a/example/shownet.html
+++ b/example/shownet.html
@@ -13,8 +13,16 @@
 </body>

 <script>
   var distance = function(force) { force.jaccardLinkLengths(100, 0.2); }
   var diagram = new Diagram('#diagram', 'shownet.json', {pop: /^([^\s-]+)-/, distance: distance});
   diagram.init('interface');
+
+  diagram.on('rendered', () => {
+    document.querySelectorAll('.node tspan').forEach((name) => {
+      name.textContent = name.textContent.replace(/^([^\s-]+)-/, '');
+    });
+  });
 </script>
 </html>
```

![image](https://user-images.githubusercontent.com/921696/50132926-c39de680-02cc-11e9-9c8d-bf5787859baa.png)
