### ISSUE TITLE
Adding onClick listeners to nodes

### ISSUE THREAD

**Issue by JahedulAnowar** [codeout/inet-henge#18]
Hi, thank you for providing us with such an amazing work.
I was just wondering if the graph can be made a bit lively, for example, adding onClick listeners to nodes which changes the assigned icon if available or assigns a new icon, or maybe clicking two nodes will change the link width or color.
If i want to do something like this, where can i start, like editing the js? 
Any hints will be appreciated as i am relatively new to coding in js.

**Comment by codeout** [comment]
I'd think that `diagram.on('render', () => {})`is good to start with.

Generally speaking, SVG DOM is similar to HTML so we can add basic event listeners but we have to wait until inet-henge finishes rendering SVG anyways.

You can implement any code to change node icons, link width, color, or anything else inside the callback function for `rendered` event like:

https://inet-henge.herokuapp.com/issue18.html

```js
<script>
  const diagram = new Diagram('#diagram', 'data/index.json', {pop: /^([^\s-]+)-/});
  diagram.init('loopback', 'interface');

  diagram.on('rendered', () => {
    document.querySelectorAll('.node').forEach((node) => {
      node.addEventListener('click', (event) => {
        // Do nothing for dragging
        if(event.defaultPrevented){
          return;
        }

        // Update icon of the first child
        const node = event.currentTarget.getElementsByTagName('image')[0];
        if (node) {
          node.setAttribute('href', './images/openflow.png');
        }
      });
    });
  });
</script>
```

:bulb: SVG will also reflect CSS changes. If you want to change styles in js I would recommend that you try it together just like web development.

**Comment by JahedulAnowar** [comment]
Thank you for your help. I tried it works.
But when i try to implement this part of code within my Django project, it doesn't seem to register the clicks. I tried to debug the code and found that `diagram.on('rendered', () => {})` is not being executed.

**Comment by codeout** [comment]
Is there any way to reproduce the problem?

**Comment by JahedulAnowar** [comment]
At this moment i am unable to share the project but if it helps you to understand, basically, what I did is simply created a Django app in which I have put your code. Django is only serving the template. Now on running the app, diagram is being rendered, dragging and zooming also works except the click event doesn't do anything.

**Comment by codeout** [comment]
Thanks. After a quick test in my environment, I confirmed that inet-henge with Django just works.
I'm afraid that it could be your project specific issue.

You can see my test code here: https://github.com/codeout/django-inethenge

**Comment by JahedulAnowar** [comment]
It seems the problem is with the way json data is accessed.
When i access json data from a file like 'index.json' on click works but when a variable containing the json is passed it doesn't work.

**Comment by codeout** [comment]
OK, I could reproduce the problem.
The root cause is that `rendered` event fires too quickly before completing `diagram.on()`, so could you try something like this? Moving `diagram.init()` to the end will help.

```js
<script>
  const diagram = new Diagram('#diagram', 'data/index.json', {pop: /^([^\s-]+)-/});

  diagram.on('rendered', () => {
    document.querySelectorAll('.node').forEach((node) => {
      node.addEventListener('click', (event) => {
        // Do nothing for dragging
        if(event.defaultPrevented){
          return;
        }

        // Update icon of the first child
        const node = event.currentTarget.getElementsByTagName('image')[0];
        if (node) {
          node.setAttribute('href', './images/openflow.png');
        }
      });
    });
  });

  diagram.init('loopback', 'interface');
</script>
```

**Comment by JahedulAnowar** [comment]
It is working now.
Thank you so much for the help.
