### ISSUE TITLE
POP object query

### ISSUE THREAD

**Issue by sngx13** [codeout/inet-henge#19]
Hi,

1st of all thank you for such a great tool! 

My question is around POP grouping, is it possible (I guess this is a feature request) to make it upper case? All of my devices are lower case and POP name is last three characters (vs example) or maybe even override this behaviour with own names?

Thank you.

**Comment by codeout** [comment]
Hi,

I think the easiest way would be `text-transform` in CSS. To transform upper cases to lower for example:

```diff
--- a/example/style.css
+++ b/example/style.css
@@ -9,6 +9,7 @@
   stroke: #fff;
   stroke-width: 1.5px;
 }
+.group text { text-transform: lowercase; }

 .node text { font-size: 10px; }
```

![image](https://user-images.githubusercontent.com/921696/86483563-45f6da00-bd8f-11ea-88cf-f1cdd54fdaef.png)

Or you can override pop names with `rendered` callback:

```diff
--- a/example/index.html
+++ b/example/index.html
@@ -11,7 +11,14 @@
   <body>
     <div id="diagram"></div>
     <script>
+     const pops = {POP01: 'foo', POP02: 'bar', POP03: 'baz'};
      const diagram = new Diagram('#diagram', 'index.json', {pop: /^([^\s-]+)-/, bundle: true});
+
+     diagram.on('rendered', () => {
+       document.querySelectorAll('.group text').forEach((i) => {
+         i.textContent = pops[i.textContent];
+       });
+     });
      diagram.init('loopback', 'interface');
     </script>
   </body>
```

![image](https://user-images.githubusercontent.com/921696/86483677-82c2d100-bd8f-11ea-9851-a2c56f7d04e6.png)

I have no plan to implement this pop name translation feature in inet-henge for now, but it should be still easy to do that outside of the library.
