### ISSUE TITLE
2 or more links between 2 nodes

### ISSUE THREAD

**Issue by atfujiwara** [codeout/inet-henge#2]
Hi, I want to draw 2 or more links between 2 nodes to show trunk links.

For example, I prepared the JSON file like below:

```
{
  "nodes": [
    { "name": "node1" },
    { "name": "node2" }
  ],

  "links": [
    { "source": "node1",  "target": "node2", 
      "meta": {
        "interface": { "source": "Eth1", "target": "Eth1" }
      }
    },
    { "source": "node1",  "target": "node2",
      "meta": {
        "interface": { "source": "Eth2", "target": "Eth2" }
      }
    }
  ]
}
```

By this, I expect 2 links are drawn between Eth1 of each nodes and between Eth2 of them. But the result was like below:

![screen shot 2018-04-05 at 16 52 50](https://user-images.githubusercontent.com/1313161/38354065-3be12c28-38f3-11e8-9614-3e416c05bfe1.png)

It seems that 2 links are overlapping. Is my JSON file is incorrect? In case of that, how can I fix it?

**Comment by codeout** [comment]
That's right, today's inet-henge draws all lines between two nodes overlapping themselves.

> I expect 2 links are drawn between Eth1 of each nodes and between Eth2 of them

I also want to do this. Let me try to implement.

**Comment by codeout** [comment]
The biggest problem I have today is that overlapped lines are better in some situation:

```
Router A ----- Router B
         ^   ^
      eth1   eth2
```

Let's say we generates a json based on the network above, probably we want to create link data on per-node basis and merge them like this:

```
{
  "nodes": [
    { "name": "Router A" },
    { "name": "Router B" }
  ],

  "links": [
    { "source": "Router A",  "target": "Router B", 
      "meta": { "interface": { ... } }  // <-- Generated by Router A configuration
    },
    { "source": "Router B",  "target": "Router A",
      "meta": { "interface": { ... } }  // <-- Generated by Router B configuration
    }
  ]
}
```

We want to have a single line when two links are identical, but it looks complicated to tell whether they are identical or not. (In particular, when no meta data is given or they are not symmetric)

**Comment by atfujiwara** [comment]
I see. I thought that kind of issues(duplicated links) should be solved by data generators.
Actually I tried but it was difficult a little.

**Comment by codeout** [comment]
I've implemented an experimental option `bundle: true`, you can draw multiple links between nodes.

```html
<script>
 var diagram = new Diagram('#diagram', 'index.json', {pop: /^([^\s-]+)-/, bundle: true});
 ...
</script>
```

![image](https://user-images.githubusercontent.com/921696/40116886-164b138e-5950-11e8-9121-b7bc373a4fc4.png)

Hope it works for you 🤞 

> We want to have a single line when two links are identical, but it looks complicated to tell whether they are identical or not. (In particular, when no meta data is given or they are not symmetric)

Today's code cannot uniq identical links, It's currently under development.
I'll change `false` to `true` for the default behavior of the `bundle` option after everything is done.

**Comment by atfujiwara** [comment]
Great! `bundle` option works well in my environment.
Of course, I need to prepare JSON file so that each link is unique. But it's ok for me because my code can do that as you may know. :wink:
I hope you will solve the identical link issue and make `bundle` option default.

**Comment by codeout** [comment]
Grad to hear it !

> my code can do that

I know your great work at https://github.com/atfujiwara/inet-archaeo
