### ISSUE TITLE
Different meta in popup for different devices

### ISSUE THREAD

**Issue by marhyno** [codeout/inet-henge#23]
Is there a way to display different meta for different Nodes ? 
E.g. I have two nodes, one is router one is switch, both have different meta but I dont want to write all meta in Diagram init.

    {
      "name": "Router",
      "meta": {
        "name": "router1",
        "hostname": "test",
        "tenant-ip": "123456,
        "admin-ip": "1.1.1.1",
        "loopback-ip": "2.2.2.2",
        "serial-number": "897564SDWQ",
        "ios-version": "16.12.2s",
        "software-type": "ios-xe",
        "hypervisor-hostname": "ESX123",
        "hypervisor-ip": "10.10.10.10",
        etc...
      },
      "icon": "../images/ios-xe.png"
    },
    {
      "name": "Switch",
      "group": "POD1",
      "meta": {
        "capabilities": "",
        "childAction": "",
        "clientEvent": "assigned",
        "configIssues": "",
	etc...
      },
      "icon": "../images/nexus9k.png"
    },

**Comment by codeout** [comment]
No, but undefined or black string meta will be omitted even if you call `init()` like this:

```js
diagram.init(
  'name',
  'hostname',
  'tenant-ip',
  'admin-ip',
  'loopback-ip',
  'serial-number',
  'ios-version',
  'software-type',
  'hypervisor-hostname',
  'hypervisor-ip',

  'capabilities',
  'childAction',
  'clientEvent',
  'configIssues',
);
```

![image](https://user-images.githubusercontent.com/921696/101233128-bec0e000-36f9-11eb-8553-2e6391c7538a.png)

![image](https://user-images.githubusercontent.com/921696/101233131-c2546700-36f9-11eb-8fd4-a2a257687813.png)
