### ISSUE TITLE
Please add escape functions for Node manipulation

### ISSUE THREAD

**Issue by marhyno** [codeout/inet-henge#25]
Because we have many connections between nodes, I decided I will use network as node. 
But encountered error in tooltip because there are special characters like dots and slash in subnet.

Decided to use, you might add CSS.escape to the tooltip.ts.
I solved it with this below.

```
nodeId(): string {
        return classify(CSS.escape((<Node>this.node).name));
}
```

**Comment by codeout** [comment]
Good point. I'll push your code after testing it. Thanks!

**Comment by codeout** [comment]
inet-henge v1.1.1 has been published with the fix.
