### ISSUE TITLE
how to make the whole graph be in the center of the webpage

### ISSUE THREAD

**Issue by chenqun61** [codeout/inet-henge#3]

**Comment by codeout** [comment]
Hi chenqun61,

You can manually zoom and move your graph with svg attribute `transform`.

### Original

![image](https://user-images.githubusercontent.com/921696/40126369-2319cad4-5968-11e8-8a40-d579b2d6ea00.png)

### Zoom

```html
  <script>
   var diagram = new Diagram('#diagram', 'index.json', {pop: /^([^\s-]+)-/, bundle: true});
   diagram.init('loopback', 'interface');
   diagram.svg.attr('transform', 'scale(0.5)');
  </script>
```

![image](https://user-images.githubusercontent.com/921696/40126407-3e13e388-5968-11e8-8cef-47c996bddc88.png)

### Zoom + Move

```html
  <script>
   var diagram = new Diagram('#diagram', 'index.json', {pop: /^([^\s-]+)-/, bundle: true});
   diagram.init('loopback', 'interface');
   diagram.svg.attr('transform', 'translate(100, 100) scale(0.5)');
  </script>
```

![image](https://user-images.githubusercontent.com/921696/40126460-58334c36-5968-11e8-840b-3ed9ef4b265d.png)

inet-henge doesn't support auto-scale or auto-scaling today.

**Comment by chenqun61** [comment]
hi ,thanks for your reply.l do follow u and there are another problem.
I can manually zoom and move my graph to be in the center of the webpage  , but when I first click on the page , it returns to its original position and size.is it a bug?what about u when u first click the page?

**Comment by codeout** [comment]
Thank you for your report. It looks like a bug. Let me take a look on this problem.

**Comment by chenqun61** [comment]
that's so kind of you, can you Repair this bug as quickly as soon ? because my project is using your good inet-henge. thank you very much.

**Comment by codeout** [comment]
I've just committed the fix. Could you try the latest version?

**Comment by chenqun61** [comment]
you rock! Thank you very much ,it works very well.

**Comment by codeout** [comment]
Sounds good :tada: Thank you too!
