### ISSUE TITLE
Zoomed View

### ISSUE THREAD

**Issue by sngx13** [codeout/inet-henge#34]
Hi, I have a 3 node topology and on the load everything appears to be zoomed out. Is there a way to load the topology zoomed in?

**Comment by codeout** [comment]
@sngx13 Yes, you can specify initial zoom ratio and coordinates.

```js
  <script>
   const diagram = new Diagram('#diagram', 'index.json', {pop: /^([^\s-]+)-/, bundle: true});
   diagram.init('loopback', 'interface');
   diagram.svg.attr('transform', 'scale(0.5)');
  </script>
```
Please see #3 for more details.

**Comment by sngx13** [comment]
That worked :) Thank you. Only issue is, it's not positioning it in the middle (off canvas initially so I have to drag it), guess that's uncontrollable?

**Comment by codeout** [comment]
Try `translate(x, y)` if your diagram size is predictable. It's a bit difficult to calculate the center of your diagram, but I hope that fixed `x` and `y` make your diagram more "acceptable".

```js
  <script>
   var diagram = new Diagram('#diagram', 'index.json', {pop: /^([^\s-]+)-/, bundle: true});
   diagram.init('loopback', 'interface');
   diagram.svg.attr('transform', 'translate(100, 100) scale(0.5)');
  </script>
```
