### ISSUE TITLE
Ajax loading data ... 

### ISSUE THREAD

**Issue by evgarik** [codeout/inet-henge#5]
Is it possible to make dynamic updating of data using ajax boot with periodic update

**Comment by codeout** [comment]
Hi, inet-henge dynamically loads .json with ajax and doesn't have a periodic update option.
But I'd think that you can do this with `setInterval()` like this:

```html
  <script>
    var diagram = new Diagram('#diagram', 'index.json', {pop: /^([^\s-]+)-/});
    diagram.init('loopback', 'interface');

    setInterval(() => {
      diagram.destroy();
      diagram.init('loopback', 'interface');
    }, 3000);  // update every 3 seconds
  </script>
```

**Comment by evgarik** [comment]
When an update occurs, the links

**Comment by codeout** [comment]
Unfortunately yes, link positions will be reset. Currently it's not supported to add nodes/links to rendered diagram without reset.

**Comment by evgarik** [comment]
if you do not add new items to the file, the offset also occurs

**Comment by MGTfang** [comment]
Hi   @codeout  If json data is updated, for example, nodes are added or removed. Is there some idea to make change on saved graph layout, only add or remove node, not reset.   ：）

**Comment by codeout** [comment]
You know, it's based on [force directed graph](https://github.com/d3/d3-force).
Needs to calculate all the node (and maybe change the positions a little bit) even when adding a single node.

In short, I have no idea to do it for now 🤔
