### ISSUE TITLE
Bug translate

### ISSUE THREAD

**Issue by evgarik** [codeout/inet-henge#7]
I use
`diagram.svg.attr('transform', 'translate(100, 100) scale(1.5)');`
It turns out to move the map. but when you try to move the map, you jump to the coordinates before moving

**Comment by codeout** [comment]
Could you try the latest version? The problem was fixed at #3.

**Comment by evgarik** [comment]
I'm using the latest version
attached to button
`diagram.svg.attr('transform', 'translate(100, 100) scale(1.5)');`

I check:
1. I move the map with the mouse
2. Click on the button
3. I try to move the map again with the mouse

the same with zoom

**Comment by codeout** [comment]
Thanks for the comment. Let me try to reproduce it.

**Comment by codeout** [comment]
I've just pushed the fix. Could you try the latest code please?

**Comment by codeout** [comment]
Try

```js
diagram.attr('transform', 'translate(100, 100) scale(1.5)');
```

instead of

```
diagram.svg.attr('transform', 'translate(100, 100) scale(1.5)');
```
